call plug#begin('~/.vim/plugged')

Plug 'davidhalter/jedi-vim'
Plug 'Yggdroot/indentLine'
Plug 'w0rp/ale'
Plug 'lifepillar/vim-solarized8'

call plug#end()

"Global
set encoding=utf8
syntax on
filetype plugin indent on

" UI
set background=dark
colorscheme solarized8_flat

set showmatch
set ruler 
set number
set showcmd
set hlsearch

"Spaceing and Indent
set tabstop=4
set smarttab
set expandtab
set shiftwidth=4
set softtabstop=4

set autoindent
set smartindent

"Touchpad
set mouse=a

"Files
set autoread

set nobackup
set nowb
set noswapfile

"Miscellaneous
set belloff=all

"jedi
let g:jedi#completions_command = "<C-N>" 
let g:indentLine_color_term = 15

"ale
let g:ale_linters = {'python':['flake8']}
let g:ale_statusline_format = ['⨉ %d', '⚠ %d', '⬥ ok']
let g:ale_sign_column_always = 1

"Python
autocmd BufNewFile *.py exec ":call SetTitle()"
func SetTitle() 
    if &filetype == "python"
        call setline(1,"#!/usr/bin/env python3")
        call setline(2,"# -* - coding: UTF-8 -* -")
    endif
endfunc
