call plug#begin('~/.vim/plugged')

Plug 'davidhalter/jedi-vim'
Plug 'Yggdroot/indentLine'
Plug 'w0rp/ale'
Plug 'lifepillar/vim-solarized8'

call plug#end()

let python_highlight_all = 1

let g:jedi#completions_command = "<C-N>" 

let g:indentLine_color_term = 15

let g:ale_linters = {'python':['flake8']}
let g:ale_statusline_format = ['⨉ %d', '⚠ %d', '⬥ ok']
let g:ale_sign_column_always = 1

set mouse=a

set tabstop=8
set expandtab
set shiftwidth=4
set softtabstop=4
set autoindent
set showmatch
set ruler 
set number
set hlsearch
set autoread
set encoding=utf8

set nobackup
set nowb
set noswapfile

set background=dark
colorscheme solarized8_flat

autocmd BufNewFile *.py exec ":call SetTitle()"
func SetTitle() 
    if &filetype == "python"
        call setline(1,"#!/usr/bin/env python3")
        call setline(2,"# -* - coding: UTF-8 -* -")
    endif
endfunc
