#!/usr/bin/env bash
# this use ip.cn and ip138.com

ip=`mtr -rn $1 -c 1|awk '$2 ~ "[12]?[0-9]?[0-9]\.[12]?[0-9]?[0-9]\.[12]?[0-9]?[0-9]\.[12]?[0-9]?[0-9]"{print $2}'`
echo -e 'IP\t\t\tip.cn\t\t\tip138.com'
for i in $ip
do
    echo -e $i'\t\t\c'
    curl -s "http://ip.cn/index.php?ip="$i | awk -F "来自：" '{printf $2"\t\t"}'
    curl -s "ip138.com/ips138.asp?ip="$i | iconv -f gbk -t utf-8 | grep class=\"ul1\" |awk -F "本站主数据：" '{print $2}'| awk -F "<" '{print $1}'
done 
